export const ACTION_TYPES = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_ROLE: 'SET_USER_ROLE',
    SET_FEEDBACK_USER: 'SET_FEEDBACK_USER',
    SET_BUS_SELECTED: 'SET_BUS_SELECTED',
    SET_BUS_DOCUMENT: 'SET_BUS_DOCUMENT',
    SET_BUS_DATA: 'SET_BUS_DATA',
    SET_REVENUE_DATA: 'SET_REVENUE_DATA',
    SET_DATE_STARTED: 'SET_DATE_STARTED',
    SET_SEARCH_DATE: ' SET_SEARCH_DATE',
    SET_SEARCH: 'SET_SEARCH',
    SET_HEALTHCARE_DATA: 'SET_HEALTHCARE_DATA',
    SET_PASSENGERS_DATA: 'SET_PASSENGERS_DATA'
}